### ISSUE TITLE
ERROR building..

### ISSUE THREAD

**Issue by andmarti1424** [dave92082/bs-patch#2]
Hello. I am having problems building the patched app.
Can you think of anything that could be wrong in my setup?
Thanks!

`[I] mongo@arch ~/Downloads/bs-p> which npm
/usr/bin/npm`

`./bs-patch 
INFO[0000] Reading config.yaml                          
INFO[0000] Finding Latest BluOS Controller              
INFO[0004] Downloading Latest BlueOS controller: https://www.bluesound.com/wp-content/uploads/2020/11/BluOS-Controller-3.12.1.dmg 
Downloading... 98 MB complete      
INFO[0283] Extracting BlueOS Controller DMG             
INFO[0285] Extracting ASAR                              
ERRO[0285] Error extracting ASAR:                       
INFO[0285] Patching electron.js                         
INFO[0285] Patching app.js - Update Check               
INFO[0285] Patching app.js - Update Platform            
INFO[0285] Adding electron dependency                   
ERRO[0285] Error installing electron:                   
INFO[0285] Adding electron-builder dependency           
ERRO[0285] Error installing electron:                   
INFO[0285] Building Snap and AppImage                   
ERRO[0285] Error extracting ASAR:                       
INFO[0285] Cleaning up                      `

**Comment by dave92082** [comment]
Please post your config.yaml file that is in the same.folder as bs-patch

**Comment by andmarti1424** [comment]
`cat config.yaml 
nodeBinPath: "/usr/bin/npm"`

both config.yaml and bs-patch are in the same directory. thanks!

**Comment by bd-david-suarez** [comment]
remove the `npm` and it should work. It needs to be the path the the `bin` folder where node is (or is linked) only:

config.yaml
```yaml
nodeBinPath: "/usr/bin"
```

**Comment by dave92082** [comment]
remove the npm and it should work. It needs to be the path to the bin folder where node is (or is linked) only:

config.yaml
```yaml
nodeBinPath: "/usr/bin"
```

**Comment by andmarti1424** [comment]
Now it continued but failed at the end with this:

> INFO[0000] Reading config.yaml                          
INFO[0000] Finding Latest BluOS Controller              
INFO[0003] Downloading Latest BlueOS controller: https://www.bluesound.com/wp-content/uploads/2020/11/BluOS-Controller-3.12.1.dmg 
Downloading... 98 MB complete      
INFO[0544] Extracting BlueOS Controller DMG             
INFO[0545] Extracting ASAR                              
INFO[0552] Patching electron.js                         
INFO[0552] Patching app.js - Update Check               
INFO[0552] Patching app.js - Update Platform            
INFO[0552] Adding electron dependency                   
INFO[0715] Adding electron-builder dependency           
INFO[0805] Building Snap and AppImage                   
ERRO[0805] Error extracting ASAR:                       
INFO[0805] Cleaning up                           

>

**Comment by dave92082** [comment]
do you have npx as well?

Please run
`which npx`

**Comment by andmarti1424** [comment]
Yes I do.output is /usr/bin/npx

**Comment by dave92082** [comment]
Ok, there is definitly a copy/paste bug [here](https://github.com/dave92082/bs-patch/blob/5faae18d4d77578a6e68685664f92a7c61906ad7/main.go#L122). The error should not state "Error extracting ASAR, it should state that it encountered an error building.

If you got to this step, everything should be prepared for you to run the last step manually and see what the error is. Do the following to see what the real error is:

1. In the folder where you have `bs-patch`, open a terminal and CD in to the `bluos` folder. You should see the package.json and other electron files. 
2. Execute `electron-builder` and see what error it gives you.

**Comment by andmarti1424** [comment]
The thing is it removes everything during cleanup.
I commented those lines in the main.go.
But it removes them anyways.. may be I have to update the patch file?

I have electron10 and electron9 but I am not finding electron-builder binary. May be thats the cause of failure..

**Comment by dave92082** [comment]
It should add electron-builder and electron ^9.0.0 as developer dependencies to the project. I thought that installing them as dev dependencies would do the trick, but you may have to install electron-builder as a global package:

`npm install electron-builder -g`

**Comment by andmarti1424** [comment]
I did:
`sudo npm install -g electron-builder`
Now I have electron-builder binary, but it still fails.
I managed to get a copy of bluos directory at some time of execution of the bs-patch

electron-builder inside it fails too, but it generated a bluos binary inside dist/linux-unpacked directory..

Any chance I can avoid the cleanup process?

**Comment by dave92082** [comment]
Make sure you restart your terminal session to ensure that electron-builder is picked up in the path...

Commenting out like 87 for `cleanUp()` should prevent the cleanup. After commenting it out, you can either build the tool yourself using:

`go build -o bs-patch main.go` or just run the code file using `go run main.go`

**Comment by andmarti1424** [comment]
electron-builder inside the bluos folder fails with this message: 
  • electron-builder  version=22.9.1 os=5.7.9-arch1-1
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246

I am still trying to understand that message..

**Comment by andmarti1424** [comment]
Forgot to mention I did restart the terminal.. Thank you for your help.
You already helped a lot.

**Comment by dave92082** [comment]
make sure that the `package.json` has electron version ^9.0.0 specified. It is stating that it couldn't detect what version of electron the bluos project is using.

The package.json should look like this:
```json
{
  "name": "BluOS",
  "productName": "BluOS Controller",
  "displayName": "BluOS Controller",
  "version": "3.12.1",
  "description": "BluOS Controller",
  "main": "main.js",
  "repository": "https://github.com/electron/electron-quick-start",
  "author": "Bluesound",
  "license": "Commercial",
  "dependencies": {
    "adm-zip": "^0.4.7",
    "bonjour": "^3.5.0",
    "chokidar": "^1.7.0",
    "electron-updater": "^4.0.6",
    "network": "^0.3.2",
    "path-is-absolute": "^1.0.1",
    "request": "^2.81.0",
    "sudo-prompt": "^7.1.0",
    "wifi-control": "^2.0.1",
    "wifi-password": "^3.0.1",
    "xml2js": "^0.4.17"
  },
  "devDependencies": {
    "electron": "^9.3.5",
    "electron-builder": "^22.9.1"
  }
}

```

**Comment by andmarti1424** [comment]
It did not have dev-dependencies at all!!!
I added them like this:


>  {
> 
>   "name": "BluOS",
>   "productName": "BluOS Controller",
>   "displayName": "BluOS Controller",
>   "version": "3.12.1",
>   "description": "BluOS Controller",
>   "main": "main.js",
>   "repository": "https://github.com/electron/electron-quick-start",
>   "author": "Bluesound",
>   "license": "Commercial",
>   "dependencies": {
>     "adm-zip": "^0.4.7",
>     "bonjour": "^3.5.0",
>     "chokidar": "^1.7.0",
>     "electron-updater": "^4.0.6",
>     "network": "^0.3.2",
>     "path-is-absolute": "^1.0.1",
>     "request": "^2.81.0",
>     "sudo-prompt": "^7.1.0",
>     "wifi-control": "^2.0.1",
>     "wifi-password": "^3.0.1",
>     "xml2js": "^0.4.17"
>   },
>   "dev-dependencies": {
>     "electron": "^9.0.0",
>     "electron-builder": "^22.9.1"
>   }
> }

But same error "Cannot compute"...

**Comment by dave92082** [comment]
after you add them, did you run `npm install` ?

**Comment by andmarti1424** [comment]
Not until you just said it. I then run it.. but still same message!

**Comment by dave92082** [comment]
Just looked back at the package json... you used the wrong key. It's `devDependencies` not `dev-dependencies` ;)

**Comment by andmarti1424** [comment]
SORRY. That was my bad. So late in here. It managed to get it built manually, with electron-builder command (failed the cleanup. see attached file).
[electron1.txt](https://github.com/dave92082/bs-patch/files/5620097/electron1.txt)

The building process generated the bluos binary in  conjunction with libraries inside dist/linux-unpacked. If I run the binary outside that directory with libraries.. it fails with the message "error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory"

**Comment by dave92082** [comment]
According to that log file, the error may be caused by this:

```  ⨯ chmod /usr/lib/node_modules/electron-builder/node_modules/app-builder-lib/templates/icons/electron-linux/256x256.png: operation not permitted```

This is why using something like NVM to manage node and it's versions is helpful. On your system, you would need sudo to build and clean since it needs access to the global modules. You can try doing `sudo electron-builder` but I would recommend looking in to NVM in teh log run.

You said that it generated the bluos binary...if it created the Snap and the .AppImage, that should be all that you need. I've never tried the linux-unpacked.

**Comment by andmarti1424** [comment]
Thank you. Doing it with sudo it built the .AppImage. Otherwise it failed.
I still cant figure out why its failing with the go patch. If its because of the devDependencies.. Why is not adding that section in the package.json..?

**Comment by dave92082** [comment]
The only reason I could think of is npm isn't working right for some reason
when bs-patch calls it

**Comment by andmarti1424** [comment]
I think you can close this. Thank you for your help!
